### ISSUE TITLE
A user should be able to create a recurring task

### ISSUE THREAD

**Issue by jrkuan** [cs2103aug2015-t11-3j/main#8]
... so that the user does not have to re-create the task again.

**Comment by jrkuan** [comment]
App able to identify recurring tasks, however unable to store saved data

@JamezMing @hung123abc

**Comment by JamezMing** [comment]
deleting and marking not in place, editing ready

**Comment by JamezMing** [comment]
added tentative version for delete/mark for recur task

**Comment by jrkuan** [comment]
Able to create a recurring task
